version: "3.5"

services:
  roscore:
    image: ros:noetic-ros-core
    container_name: roscore
    tty: true
    stdin_open: true
    environment:
      - ROS_MASTER_URI=http://roscore:11311
    command: roscore


    # Developement docker with ROS
  kortex-ros:
    build:
      context: .
    container_name: kortex-ros
    restart: always
    stdin_open: true
    tty: true
    environment:
      - ROS_MASTER_URI=http://roscore:11311
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/dri:/dev/dri
      - /dev/input:/dev/input
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./kortex_joystick_demo:/app/ros_ws/src/kortex_joystick_demo
    command: roslaunch kortex_joystick_demo kortex_joystick_demo.launch
    # command: tail -F anything