x-net-config:
  &net-config
  network_mode: host
  env_file: net.env

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:

  rviz:
    image: husarion/rviz:noetic
    container_name: rviz
    restart: on-failure
    <<: [ *net-config, *cpu-config ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/kinova_config.rviz:/root/.rviz/default.rviz
      - ./../ros_entrypoint.sh:/ros_entrypoint.sh
      - description-volume:/ros_ws

volumes:
  description-volume:
