services:

  kortex-ros:
    image: husarion/kortex-joystick:noetic
    container_name: kortex-ros
    restart: on-failure
    network_mode: host
    environment:
      - ROS_IP=${ROS_IP:-10.15.20.3}
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://10.15.20.2:11311}
    devices:
      - /dev/input:/dev/input
    volumes:
      - description-volume:/ros_ws
    command: >
      roslaunch kortex_joystick_demo kortex_joystick_demo.launch
        robot_ip_address:=10.15.20.4

volumes:
  description-volume:
