x-net-config:
  &net-config
  network_mode: host
  env_file: net.env

services:

  realsense-camera:
    image: husarion/realsense:noetic--20230522
    container_name: realsense-camera
    restart: on-failure
    <<: *net-config
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    command: >
      roslaunch realsense2_camera rs_rgbd.launch 
        camera:=rs_camera 
        tf_prefix:=rs_camera
