services:

  gamepad_controller:
    image: husarion/joy2twist:noetic-1.0.0-20230728-stable
    container_name: gamepad_controller
    restart: on-failure
    network_mode: host
    environment:
      - ROS_IP=${ROS_IP:-10.15.20.3}
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://10.15.20.2:11311}
    devices:
      - /dev/input/js0
    command: >
      roslaunch --wait joy2twist gamepad_controller.launch
        joy2twist_params_file:=$$(find joy2twist)/config/joy2twist_panther.yaml
