x-net-config:
  &net-config
  network_mode: host
  env_file: net.env

services:

  ouster-lidar:
    image: husarion/ouster:melodic
    container_name: ouster-ros
    restart: on-failure
    <<: *net-config
    command: >
      roslaunch ouster_ros sensor.launch
        timestamp_mode:=TIME_FROM_ROS_TIME
        metadata:=/ouster_metadata.json
        viz:=false
        sensor_hostname:=${OUSTER_IP_ADDERSS}
        lidar_mode:=${OUSTER_LIDAR_MODE}
