services:

  rviz:
    # image: husarion/rviz:noetic
    build:
      context: .
      dockerfile: Dockerfile.rviz
    container_name: rviz
    restart: on-failure
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/kinova_config.rviz:/root/.rviz/default.rviz
      - description-volume:/ros_ws
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    command: 
      - /bin/bash
      - -c
      - |
        source /ros_ws/devel/setup.bash
        rosrun rviz rviz 

volumes:
  description-volume: