x-net-config:
  &net-config
  network_mode: host
  env_file: net.env

services:

  kortex-ros:
    image: kinova_test
    container_name: kortex-ros
    restart: on-failure
    <<: *net-config
    devices:
      - /dev/input:/dev/input
    volumes:
      - description-volume:/ros_ws
      - ../kortex_joystick_demo/launch:/ros_ws/src/kortex_joystick_demo/launch
    command: >
      roslaunch kortex_joystick_demo kortex_joystick_demo.launch
        robot_ip_address:=${KINOVA_IP_ADDRESS}
        arm:=${KINOVA_ARM_MODEL}

volumes:
  description-volume:
