x-common-config:
  &common-config
  network_mode: host
  restart: on-failure
  tty: true
  environment:
    - ROS_IP=10.15.20.3
    - ROS_MASTER_URI=http://10.15.20.2:11311

services:

  kortex-ros:
    image: husarion/kortex-joystick:noetic
    container_name: kortex-ros
    <<: *common-config
    devices:
      - /dev/input:/dev/input
    volumes:
      - description-volume:/ros_ws
    command: >
      roslaunch kortex_joystick_demo kortex_joystick_demo.launch
        robot_ip_address:=10.15.20.4

  ouster-lidar:
    image: husarion/ouster:melodic
    container_name: ouster-ros
    <<: *common-config
    command: >
      roslaunch ouster_ros sensor.launch
        timestamp_mode:=TIME_FROM_ROS_TIME
        metadata:=/ouster_metadata.json
        viz:=false
        sensor_hostname:=10.15.20.10
        lidar_mode:=1024x20

  realsense-camera:
    image: husarion/realsense:noetic--20230522
    container_name: realsense-camera
    <<: *common-config
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    command: >
      roslaunch realsense2_camera rs_rgbd.launch 
        camera:=rs_camera 
        tf_prefix:=rs_camera

  rviz:
    image: husarion/rviz:noetic
    container_name: rviz
    <<: *common-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/kinova_config.rviz:/root/.rviz/default.rviz
      - ./../ros_entrypoint.sh:/ros_entrypoint.sh
      - description-volume:/ros_ws
    environment:
      - DISPLAY=${DISPLAY:?Source of setup_virtual_desktop.sh required!}
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311

  remote-desktop:
    image: donowak/remote-desktop:lan
    container_name: vnc-remote-desktop
    restart: on-failure
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ipc: host
    ports:
      - 8080:8080
    environment:
      - DISPLAY=${DISPLAY:?Source of setup_virtual_desktop.sh required!}
      - VNC_PASSWORD=husarion
  
volumes:
  description-volume:
